@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDA3MWQ0ZmNmM2E3MDdhODViMDUyNjMiLCJpYXQiOjE2MTEzOTM1MDB9.0JUQuUN5MtLZKucgY4yqA2e89hy4iLpw7P73BPmx9dI
# @ip = http://192.46.214.45:9080/api/v1/
@ip = http://localhost:3334/api/


############## Term and condition API ADMIN SIGNUP
POST {{ip}}users/signup HTTP/1.1
Content-type: application/json

{
   "firstName": "Akshay",
   "lastName": "Jain",
   "email": "coolakshayjain557@gmail.com",
   "password": "123456",
   "mobile": 1234567890,
   "countryCode":91
}

###################################################### MENU ###########################################

############ getMenuList ########

POST {{ip}}menuModule/getMenuList HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "userRole":["test1"]
}

###################################################### CREATE ROLE ###########################################

############ craeteUserRole ########

POST {{ip}}role/createUserRole HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id": null,
   "name": "testUser",
   "rights": ["60cd51d29929671c8cbe390c", "60cd50f49929671c8cbe3908"],
   "status": true,
   "createdBy": "60cdd398285f20226c9345c8",
   "updatedBy": "60cdd398285f20226c9345c8"
}

############ createUserRole ########

POST {{ip}}role/createUserRole HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id": "60cdfef4065fd802c4478671",
   "name": "testUser1",
   "rights": ["60cd51d29929671c8cbe390c", "60cd50f49929671c8cbe3908"],
   "status": true,
   "createdBy": "60cdd398285f20226c9345c8",
   "updatedBy": "60cd51d29929671c8cbe390c"
}

############ updateUserRole ########

POST {{ip}}role/updateStatusUserRole HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id": "60cdfef4065fd802c4478671",
   "status": false,
   "updatedBy": "60cd51d29929671c8cbe390c"
}

############ userRoleList ########

POST {{ip}}role/userRoleList HTTP/1.1
Content-type: application/json
Authorization: {{token}}


################# createCallback ################

POST {{ip}}callback/createCallbackRequest HTTP/1.1
Content-type: application/json

{
   "productId": "60d7dc32d31ee41430c4fac8",
   "name": "Akshay jain",
   "email": "akshay@gmail.com",
   "phone": "0123456789",
   "message": "test demo",
   "isVisit": true
}

################# getCallback ################

POST {{ip}}callback/getCallbackRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}


################# updateCallbackStatus ################

POST {{ip}}callback/updateCallbackStatusRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id": "60d5df5e1649070c68ba001e",
   "status": false
}

################# createEnquiry #################

POST {{ip}}enquiry/createEnquiryRequest HTTP/1.1
Content-type: application/json

{
   "name": "Akshay jain",
   "email": "akshay@gmail.com",
   "phone": "0123456789",
   "place": "Bangalore"
}

################# getEnquiry ################

POST {{ip}}enquiry/getEnquiryRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}


################# updateEnquiryStatus ################

POST {{ip}}enquiry/updateEnquiryStatusRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id": "60d68cbbefcf390848f994fa",
   "status": false
}


################# createreview ################

POST {{ip}}review/createReviewRequest HTTP/1.1
Content-type: application/json

{
   "productId": "60d7dc32d31ee41430c4fac8",
   "name": "Akshay jain",
   "email": "akshayq@gmail.com",
   "comment": "test demo",
   "rating": "5"
}

################# getReview ################

POST {{ip}}review/getReviewRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}


################# updateReviewStatus ################

POST {{ip}}review/updateReviewStatusRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id": "60d7171f51113a1998714a8c",
   "status": false
}

################# createproperty ################

POST {{ip}}property/createPropertyRequest HTTP/1.1
Content-type: application/json

{
   "propertyName": "TEST",
   "propertyAddress": "Bangalore",
   "propertyArea": "1200",
   "bedRoom": "3",
   "kitchen": "2"
}

################# getProperty ################

POST {{ip}}property/getPropertyRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}


################# updatePropertyStatus ################

POST {{ip}}property/updatePropertyStatusRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id": "60d7dc32d31ee41430c4fac8",
   "status": true
}

################# createfeedback ################

POST {{ip}}feedback/createFeedbackRequest HTTP/1.1
Content-type: application/json

{
   "name": "TEST",
   "rating":"5",
   "message":"demo test",
   "productId": "60d7dc32d31ee41430c4fac8"
}

################# getFeedback ################

POST {{ip}}feedback/getFeedbackRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}


################# updateFeedbackStatus ################

POST {{ip}}feedback/updateFeedbackStatusRequest HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
   "id": "60d7dc32d31ee41430c4fac8",
   "status": true
}