/**
 * All Action Keys will go here
 */
const ACTION_KEYS = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR:   'LOGIN_ERROR',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',

    GET_PROPERTY_LIST_REQUEST: 'GET_PROPERTY_LIST_REQUEST',
    GET_PROPERTY_LIST_SUCCESS: 'GET_PROPERTY_LIST_SUCCESS',
    GET_PROPERTY_LIST_ERROR: 'GET_PROPERTY_LIST_ERROR',

    GET_PROPERTY_DETAIL_REQUEST: 'GET_PROPERTY_DETAIL_REQUEST',
    GET_PROPERTY_DETAIL_SUCCESS: 'GET_PROPERTY_DETAIL_SUCCESS',
    GET_PROPERTY_DETAIL_ERROR: 'GET_PROPERTY_DETAIL_ERROR',
}

export default ACTION_KEYS;