/**
 * All Action Keys will go here
 */
const ACTION_KEYS = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    FORGOT_REQUEST: 'FORGOT_REQUEST',
    FORGOT_SUCCESS: 'FORGOT_SUCCESS',
    FORGOT_ERROR: 'FORGOT_ERROR',

    NEW_PASSWORD_REQUEST: 'NEW_PASSWORD_REQUEST',
    NEW_PASSWORD_SUCCESS: 'NEW_PASSWORD_SUCCESS',
    NEW_PASSWORD_ERROR: 'NEW_PASSWORD_ERROR',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',

    GET_PROPERTY_LIST_REQUEST: 'GET_PROPERTY_LIST_REQUEST',
    GET_PROPERTY_LIST_SUCCESS: 'GET_PROPERTY_LIST_SUCCESS',
    GET_PROPERTY_LIST_ERROR: 'GET_PROPERTY_LIST_ERROR',

    GET_PROPERTY_DETAIL_REQUEST: 'GET_PROPERTY_DETAIL_REQUEST',
    GET_PROPERTY_DETAIL_SUCCESS: 'GET_PROPERTY_DETAIL_SUCCESS',
    GET_PROPERTY_DETAIL_ERROR: 'GET_PROPERTY_DETAIL_ERROR',

    POST_PROPERTY_REQUEST: 'POST_PROPERTY_REQUEST',
    POST_PROPERTY_SUCCESS: 'POST_PROPERTY_SUCCESS',
    POST_PROPERTY_ERROR: 'POST_PROPERTY_ERROR',
    RESET_POST_PROPERTY_RESULT: 'RESET_POST_PROPERTY_RESULT',

    CONTACTUS_REQUEST: 'CONTACTUS_REQUEST',
    CONTACTUS_SUCCESS: 'CONTACTUS_SUCCESS',
    CONTACTUS_ERROR: 'CONTACTUS_ERROR',

    ENQUIRY_REQUEST: 'ENQUIRY_REQUEST',
    ENQUIRY_SUCCESS: 'ENQUIRY_SUCCESS',
    ENQUIRY_ERROR: 'ENQUIRY_ERROR',

    SITEVISIT_REQUEST: 'SITEVISIT_REQUEST',
    SITEVISIT_SUCCESS: 'SITEVISIT_SUCCESS',
    SITEVISIT_ERROR: 'SITEVISIT_ERROR',
}

export default ACTION_KEYS;