/**
 * All Action Keys will go here
 */
const ACTION_KEYS = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR:   'LOGIN_ERROR',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',

    PROPERTY_LIST_REQUEST: 'PROPERTY_LIST_REQUEST',
    PROPERTY_LIST_SUCCESS: 'PROPERTY_LIST_SUCCESS',
    PROPERTY_LIST_ERROR: 'PROPERTY_LIST_ERROR',

    SIDE_MENU_LIST_REQUEST: 'SIDE_MENU_LIST_REQUEST',
    SIDE_MENU_LIST_SUCCESS: 'SIDE_MENU_LIST_SUCCESS',
    SIDE_MENU_LIST_ERROR: 'SIDE_MENU_LIST_ERROR',

    MODULE_RIGHTS_REQUEST: 'MODULE_RIGHTS_REQUEST',
    MODULE_RIGHTS_SUCCESS: 'MODULE_RIGHTS_SUCCESS',
    MODULE_RIGHTS_ERROR: 'MODULE_RIGHTS_ERROR',


}

export default ACTION_KEYS;